apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      server {
        listen 80;
        return 301 https://$host$request_uri;
      }

      server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/cert.crt;
        ssl_certificate_key /etc/nginx/certs/cert.key;

        location / {
          proxy_pass http://node-app:3000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /private {
          auth_basic "Restricted Access";
          auth_basic_user_file /etc/nginx/.htpasswd;
          proxy_pass http://node-app:3000;
        }
      }
    }